language: python
python:
  - "2.6"
  - "2.7"
install:
  - pip install -r python/test_requirements.txt --use-mirrors
compiler:
  - gcc
  - clang
script: flake8 --exclude=jedi --select=F,C9 --max-complexity=10 python && nosetests python && ./install.sh
env:
  - YCM_TESTRUN=1 EXTRA_CMAKE_ARGS=""
  - YCM_TESTRUN=1 EXTRA_CMAKE_ARGS="-DUSE_CLANG_COMPLETER=ON"
